base_url = "https://wjy9902.github.io/ai-daily/"
title = "甲鱼AI日报"
generate_feeds = true
feed_filenames = ["rss.xml"]
theme = "even"
taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]
[extra]
even_title = "甲鱼AI日报"
even_menu = [
    {url = "/ai-daily/", name = "Home"},
    {url = "/ai-daily/tags/top/", name = "Top"},
]
[markdown]
highlight_code = true
render_emoji = true
